$('#autoGeneratedID').dataTable({
  "columnDefs": [
    { "orderable": false, "targets": 3 }
  ]
} );
$('#autoGeneratedID td').attr('role', 'gridcell');
$('#autoGeneratedID tr').attr('role', 'row');
$('#autoGeneratedID th').attr('role', 'gridcell');
$('#autoGeneratedID table').attr('role', 'grid');
$('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');
/*$('#autoGeneratedID').on('page.dt', function(){
  $('#autoGeneratedID tr:nth-of-type(2)').focus();
});*/




//donc hna n3awed n3ayet lscript lakhor ? mais amtenjemch psk hed js att