

$('#autoGeneratedID').Tabledit({
    url: 'pro.php',
    deleteButton:true,
    saveButton: false,
    autoFocus: true,
   buttons: {
        edit: {
            //   html: '<span class="glyphicon glyphicon-pencil"></span> &nbsp Modifier',

            action: 'edit'
        },
       //bouton supprimer
       delete: {
           //  html: '<span class="glyphicon glyphicon-trash"></span> &nbsp Supprimer',
           action: 'delete'
       },
       confirm: {
           //    class: 'btn btn-sm btn-danger',
           html: 'Êtes-vous sûr?'
       }


    },
    columns: {
        identifier: [0, 'idMEDECIN'],
        editable: [[1, 'nom'], [2, 'prenom'], [3, 'adresse'], [4, 'grade'], [5, 'specialite'], [6, 'telephone']]
    },

    onDraw: function() {
        console.log('onDraw()');
    },
    onSuccess: function(data, textStatus, jqXHR) {
        console.log('onSuccess(data, textStatus, jqXHR)');
        console.log(data);
        console.log(textStatus);
        console.log(jqXHR);
    },
    onFail: function(jqXHR, textStatus, errorThrown) {
        console.log('onFail(jqXHR, textStatus, errorThrown)');
        console.log(jqXHR);
        console.log(textStatus);
        console.log(errorThrown);
    },
    onAlways: function() {
        console.log('onAlways()');
    },
    onAjax: function(action, serialize) {
        console.log('onAjax(action, serialize)');
        console.log(action);
        console.log(serialize);
    }

});
