<?php


if(isset($_POST['insert'])){
    
    
$nblit=$_POST['nblit'];
    
    
$dbh = new PDO("mysql:host=localhost;dbname=service", "root", "");
$dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    
    
$stmt = $dbh->prepare("INSERT INTO chambre (nombreLit) VALUES ('".$nblit."')");
    if($stmt->execute())
    {
       header("location: chambre.php") ;
        
    }
    
    
    
    
    
    
    
}



?>
<html>

<div>
    <link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="home.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>


    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <?php
    include 'home.php';
    ?>
</div>
<!--Formulaire-->

<div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Informations chambre</h2>
            </div>
            <div class="modal-body">

                <br/>
                <form method="post" id="insert_form">
                    <h4><b><u>Informations Chambre :</u></b></h4>
                    <label>Nombre de Lit</label>
                    
                    <input type="text" name="nblit"  class="form-control" />
                    <input type="hidden" name="id" id="id" />
                    <input type="submit" name="insert" id="insert" value="Valider" class="btn btn-primary"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

            </div>
        </div>
    </div>
</div>





<!-- la liste patients "table" -->

<div align="center">
    <h2>Liste des chambres</h2>
</div>
<div align="right">

    <!--btn ajouter-->
    <button type="button" name="ajout" id="ajout" class="btn btn-primary" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>
<div class="table-responsive" id="table_patient">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idCHAMBRE" role="gridcell" >Numero de chambre</th>
            <th id="nombreLit" role="gridcell">Nombre de Lit</th>
            <th id="nbOccuped" role="gridcell">Occuped</th>
            
            <th>Liberer</th>

        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM chambre');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="idCHAMBRE" role="gridcell" ><?php echo $donne['idCHAMBRE'];?></td>
                <td id="nombreLit" role="gridcell"><?php echo $donne['nombreLit'];?></td>
                <td id="nbOccuped" role="gridcell"><?php echo $donne['nbOccuped'];?></td>
              
                
                
                <td>

                    <div class="btn-group">
                       

                            <input type="button" name="edit" value="Liberer" id="<?php echo $donne["idCHAMBRE"];?>"
                                       class="btn btn-info btn-md delete_data btn-block"/>


                 
                       
                    </div>


                </td>
               
            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<!-- pose problème <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>


<script>
    $(document).on('click', '.delete_data', function(){
        var id = $(this).attr("id");
        if(confirm("êtes vous sûr de liberer un lit?"))
        {
            $.ajax({
                url:"decrementer.php",
                method:"POST",
                data:{id:id},
                success:function(data){
                    window.location.reload();

                }
            });}});
    </script>

    
    
    </html>
<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
