

<div>
    <link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="home.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>


    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<?php
include 'home.php';
?>

    <!--Formulaire d'ajout-->
    <div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Ajouter un infirmier</h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="insert_form" action="ajouterInfirmier.php">

                        <label>Nom</label>
                        <input type="text" name="nom_i" id="nom" class="form-control" />
                        <br/>

                        <label>Prénom</label>
                        <input type="text" name="prenom_i" id="prenom" class="form-control" />
                        <br/>

                        <label>Spécialité</label>
                        <select name="specialite_i" id="specialite" class="form-control">
                            <option value="Cardiologue">Cardiologue</option>
                            <option value="Interniste">Interniste</option>
                            <option value="Hémathologue">Hémathologue</option>
                            <option value="Généraliste">Généraliste</option>
                        </select>
                        <br/>

                        <label>Téléphone</label>
                        <input type="text" name="numTel_i" id="numTel" class="form-control" />
                        <br/>

                        <label>Adresse</label>
                        <textarea name="adresse_i" id="adresse" class="form-control"></textarea>
                        <br/>

                        <label>Nom d'utilisateur</label>
                        <input type="text" name="user" id="user" class="form-control"/>
                        <br/>

                        <label>Mot de passe</label>
                        <input type="password" name="password" id="password" class="form-control"/>
                        <br/>

                        <input type="hidden" name="id" id="id" />
                        <input type="submit" name="insert" id="insert" value="Valider" class="btn btn-primary" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

                </div>
            </div>
        </div>
    </div>

</div>


<!-- ici on affiche le tableau -->

<div align="center">
    <h2>Liste infirmiers</h2>
</div>
<div align="right">
    <button type="button" class="btn btn-primary" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>

<div class="table-responsive" id="table_infirmier">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">

        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idINFIRMIER" role="gridcell" style="display:none">ID</th>
            <th id="nom_i" role="gridcell">Nom</th>
            <th id="prenom_i" role="gridcell">Prénom</th>
            <th id="adresse_i" role="gridcell">Adresse</th>
            <th id="specialite_i" role="gridcell">Spécialité</th>
            <th id="numTel_i" role="gridcell">Téléphone</th>
            <th id="action" role="gridcell">Actions</th>


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM infirmier');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell" style="display:none"><?php echo $donne['idINFIRMIER'];?></td>
                <td id="nom_i" role="gridcell"><?php echo $donne['nom_i'];?></td>
                <td id="prenom_i" role="gridcell"><?php echo $donne['prenom_i'];?></td>
                <td id="adresse_i" role="gridcell"><?php echo $donne['adresse_i'];?></td>
                <td id="specialite_i" role="gridcell"><?php echo $donne['specialite_i'];?></td>
                <td id="numTel_i" role="gridcell"><?php echo $donne['numTel_i'];?></td>
                <td>

                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary btn-lm dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">

                            <li><input type="button" name="edit" value="Modifier" id="<?php echo $donne["idINFIRMIER"];?>"
                                       class="btn btn-warning btn-md edit_data btn-block"/></li>


                            <li><input type="button" name="delete" value="Supprimer" id="<?php echo $donne["idINFIRMIER"];?>"
                                       class="btn btn-danger btn-md delete_data btn-block"/></li>
                        </ul>
                    </div>
                </td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');

    });

    //bouton ajouter

    $('#ajout').click(function () {
        $('#insert').val("Valider");
        $('#insert_form')[0].reset();
    });


    /******************** bouton modifier*********************/

    $(document).on('click', '.edit_data', function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "afficheModifierInf.php",
            method: "POST",
            data: {id: id},
            dataType: "json",
            success: function (data) {
                //remplir les cases avec les anciens données
                $('#nom').val(data.nom_i);
                $('#prenom').val(data.prenom_i);
                $('#adresse').val(data.adresse_i);
                $('#numTel').val(data.numTel_i);
                $('#specialite').val(data.specialite_i);


                $('#id').val(data.idINFIRMIER);

                $('#insert').val("Modifier");
                $('#add_data_Modal').modal('show');


            }

        });
    });


    /****Supprimer****/

    $(document).on('click','.delete_data', function(){

        var id=$(this).attr("id");
        if(confirm("êtes-vous sûr de supprimer cet infirmer?")){

            $.ajax({
                url:'suppInf.php',
                type: 'POST',
                data:{
                    ids:id
                },
                success: function(result){
                    if(result.trim() == "success")
                        window.location.reload();
                    else alert(result.trim());

                }
            });



        }
    });


</script>

