<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">


    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>

    <link rel="stylesheet" href="css/style.css">

</head>

<body>
<?php
include 'home.html';
?>
<!-- ici on affiche le tableau -->
<div class="table-responsive" id="table_medecin">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <caption class="sr-only">Liste des infirmiers.</caption>
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idINFIRMIER" role="gridcell">ID</th>
            <th id="nom_i" role="gridcell">Nom</th>
            <th id="prenom_i" role="gridcell">Prénom</th>
            <th id="adresse_i" role="gridcell">Adresse</th>
            <th id="specialite_i" role="gridcell">Spécialité</th>
            <th id="numTel_i" role="gridcell">Téléphone</th>


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM infirmier');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell"><?php echo $donne['idINFIRMIER'];?></td>
                <td id="nom_i" role="gridcell"><?php echo $donne['nom_i'];?></td>
                <td id="prenom_i" role="gridcell"><?php echo $donne['prenom_i'];?></td>
                <td id="adresse_i" role="gridcell"><?php echo $donne['adresse_i'];?></td>
                <td id="specialite_i" role="gridcell"><?php echo $donne['specialite_i'];?></td>
                <td id="numTel_i" role="gridcell"><?php echo $donne['numTel_i'];?></td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>


<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){
        $('#autoGeneratedID').Tabledit({
            url:'modifierInf.php',
            columns:{
                identifier:[0, "idINFIRMIER"],
                editable:[[1, 'nom_i'], [2, 'prenom_i'],[3, 'adresse_i'],[4, 'specialite_i'], [5, 'numTel_i']]
            },
            restoreButton:false,
            onSuccess:function(data, textStatus, jqXHR)
            {
                if(data.action == 'delete')
                {
                    $('#'+data.id).remove();
                }
            }
        });


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

</script>
<!--pour afficher les btn delete et edit-->
<script src="js/jquery/jquery.tabledit.js"></script>

</body>

</html>
