<div>

<?php
include 'home.php';
?>
<!-- ici on affiche le tableau -->

<div align="center">
    <h2>Liste occupation</h2>
</div>

<br/>

<div class="table-responsive" id="table_occupation">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">

        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idOccupation" role="gridcell">ID</th>
            <th id="lit" role="gridcell">Lit</th>
            <th id="dateD" role="gridcell">date de début</th>
            <th id="dateF" role="gridcell">date de fin</th>
            <th id="nom_p" role="gridcell">Nom</th>
            <th id="prenom_p" role="gridcell">Prenom</th>


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM patient RIGHT JOIN occupation ON patient.idPATIENT = occupation.idPatient');

        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell"><?php echo $donne['idOCCUPATION'];?></td>
                <td id="lit" role="gridcell"><?php echo $donne['lit'];?></td>
                <td id="dateD" role="gridcell"><?php echo $donne['dateD'];?></td>
                <td id="dateF" role="gridcell"><?php echo $donne['dateF'];?></td>
                <td id="nom_p" role="gridcell"><?php echo $donne['nom_p'];?></td>
                <td id="prenom_p" role="gridcell"><?php echo $donne['prenom_p'];?></td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>


<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){
        $('#autoGeneratedID').Tabledit({
            url:'modifierOccupation.php',
            columns:{
                identifier:[0, "idOCCUPATION"],
                editable:[[1, 'lit'], [2, 'dateD'],[3, 'dateF']]
            },
            restoreButton:false,
            onSuccess:function(data, textStatus, jqXHR)
            {
                if(data.action == 'delete')
                {
                    $('#'+data.id).remove();
                }
            }
        });


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

</script>
<!--pour afficher les btn delete et edit-->
<script src="js/jquery/jquery.tabledit.js"></script>

