<div>
    <link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="home.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>


    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<?php
include 'home.php';
?>


<!-- Formulaire d'ajout -->

    <!-- formlaire-->
    <div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Ajouter secrétaire</h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="insert_form" action="ajouterSecretaire.php">

                        <label>Nom</label>
                        <input type="text" name="nom_s" id="nom" class="form-control" />
                        <br/>

                        <label>Prénom</label>
                        <input type="text" name="prenom_s" id="prenom" class="form-control" />
                        <br/>

                        <label>Téléphone</label>
                        <input type="text" name="numTel_s" id="numTel" class="form-control" />
                        <br/>

                        <label>Niveau</label>
                        <textarea name="niveau_s" id="niveau" class="form-control"></textarea>
                        <br/>

                        <label>Adresse</label>
                        <textarea name="adresse_s" id="adresse" class="form-control"></textarea>
                        <br/>

                        <label>Nom d'utilisateur</label>
                        <input type="text" name="user" id="user" class="form-control"/>
                        <br/>

                        <label>Mot de passe</label>
                        <input type="password" name="password" id="password" class="form-control"/>
                        <br/>
                        <input type="hidden" name="id" id="id" />

                        <input type="submit" name="insert" id="insert" value="Valider" class="btn btn-primary" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

                </div>
            </div>
        </div>
    </div>

</div>


<div align="center">
    <h2>Liste Secrétaires</h2>
</div>
<div align="right">
    <button type="button" name="ajout" id="ajout" class="btn btn-primary" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>
<div class="table-responsive" id="table_secretaire">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idSECRETAIRE" role="gridcell" style="display:none">ID</th>
            <th id="nom_s" role="gridcell">Nom</th>
            <th id="prenom_s" role="gridcell">Prénom</th>
            <th id="numTel_s" role="gridcell">Téléphone</th>
            <th id="niveau_s" role="gridcell">Niveau</th>
            <th id="adresse_s" role="gridcell">Adresse</th>
            <th id="action" role="gridcell">Actions</th>


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM secretaire');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell" style="display:none"><?php echo $donne['idSECRETAIRE'];?></td>
                <td id="nom_m" role="gridcell"><?php echo $donne['nom_s'];?></td>
                <td id="prenom_m" role="gridcell"><?php echo $donne['prenom_s'];?></td>
                <td id="numTel_m" role="gridcell"><?php echo $donne['numTel_s'];?></td>
                <td id="niveau_m" role="gridcell"><?php echo $donne['niveau_s'];?></td>
                <td id="adresse_m" role="gridcell"><?php echo $donne['adresse_s'];?></td>
                <td id="action" role="gridcell">

                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary btn-lm dropdown-toggle" data-toggle="dropdown">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">

                            <li><input type="button" name="edit" value="Modifier" id="<?php echo $donne["idSECRETAIRE"];?>"
                                       class="btn btn-warning btn-md edit_data btn-block"/></li>


                            <li><input type="button" name="delete" value="Supprimer" id="<?php echo $donne["idSECRETAIRE"];?>"
                                       class="btn btn-danger btn-md delete_data btn-block"/></li>
                        </ul>
                    </div>

                </td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){



        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

    //bouton ajouter

    $('#ajout').click(function () {
        $('#insert').val("Valider");
        $('#insert_form')[0].reset();
    });


    /******************** bouton modifier*********************/

    $(document).on('click', '.edit_data', function () {
        var id = $(this).attr("id");
        $.ajax({
            url: "affichModifierSec.php",
            method: "POST",
            data: {id: id},
            dataType: "json",
            success: function (data) {
                //remplir les cases avec les anciens données
                $('#nom').val(data.nom_s);
                $('#prenom').val(data.prenom_s);
                $('#numTel').val(data.numTel_s);
                $('#niveau').val(data.niveau_s);
                $('#adresse').val(data.adresse_s);


                $('#id').val(data.idSECRETAIRE);

                $('#insert').val("Modifier");
                $('#add_data_Modal').modal('show');


            }

        });
    });


    /****Supprimer****/

    $(document).on('click','.delete_data', function(){

        var id=$(this).attr("id");
        if(confirm("êtes-vous sûr de supprimer ce secrétaire?")){

            $.ajax({
                url:'suppSec.php',
                type: 'POST',
                data:{
                    ids:id
                },
                success: function(result){
                    if(result.trim() == "success")
                        window.location.reload();
                    else alert(result.trim());

                }
            });



        }
    });


</script>
<!--pour afficher les btn delete et edit-->
<script src="js/jquery/jquery.tabledit.js"></script>

