<div>
    <link href="css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="home.css"/>
    <link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>


    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<?php
include 'home.php';
?>


<!-- Formulaire d'ajout -->

    <!-- formlaire-->
    <div id="add_data_Modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Ajouter secrétaire</h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="insert_form" action="ajouterSecretaire.php">

                        <label>Nom</label>
                        <input type="text" name="nom_s" id="nom" class="form-control" />
                        <br/>

                        <label>Prénom</label>
                        <input type="text" name="prenom_s" id="prenom" class="form-control" />
                        <br/>

                        <label>Téléphone</label>
                        <input type="text" name="numTel_s" id="numTel" class="form-control" />
                        <br/>

                        <label>Niveau</label>
                        <textarea name="niveau_s" id="niveau" class="form-control"></textarea>
                        <br/>

                        <label>Adresse</label>
                        <textarea name="adresse_s" id="adresse" class="form-control"></textarea>
                        <br/>

                        <label>Nom d'utilisateur</label>
                        <input type="text" name="user" id="user" class="form-control"/>
                        <br/>

                        <label>Mot de passe</label>
                        <input type="password" name="password" id="password" class="form-control"/>
                        <br/>

                        <input type="submit" name="Ajouter" id="ajouter" value="Valider" class="btn btn-primary" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>

                </div>
            </div>
        </div>
    </div>

</div>


<div align="center">
    <h2>Liste Secrétaires</h2>
</div>
<div align="right">
    <button type="button" class="btn btn-primary" onclick="$('#add_data_Modal').modal('show');">
        <i class="fa fa-plus"></i>Ajouter</button>
</div>
<br/>
<div class="table-responsive" id="table_secretaire">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <!-- le head du tableau-->
        <thead>
        <tr>
            <th id="idSECRETAIRE" role="gridcell">ID</th>
            <th id="nom_s" role="gridcell">Nom</th>
            <th id="prenom_s" role="gridcell">Prénom</th>
            <th id="numTel_s" role="gridcell">Téléphone</th>
            <th id="niveau_s" role="gridcell">Niveau</th>
            <th id="adresse_s" role="gridcell">Adresse</th>


        </tr>
        </thead>
        <tbody>
        <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try{
            $bdd = new PDO('mysql:host=localhost;dbname=service;charset=utf8','root','') ;
        }catch(Exception $e){
            echo "errreur" ;
        }

        $r=$bdd->query('SELECT * FROM secretaire');
        $row_count = 1;
        while($donne=$r->fetch()){
            ?>
            <tr>

                <td id="ids" role="gridcell"><?php echo $donne['idSECRETAIRE'];?></td>
                <td id="nom_m" role="gridcell"><?php echo $donne['nom_s'];?></td>
                <td id="prenom_m" role="gridcell"><?php echo $donne['prenom_s'];?></td>
                <td id="numTel_m" role="gridcell"><?php echo $donne['numTel_s'];?></td>
                <td id="niveau_m" role="gridcell"><?php echo $donne['niveau_s'];?></td>
                <td id="adresse_m" role="gridcell"><?php echo $donne['adresse_s'];?></td>

            </tr>
            <?php
            $row_count ++ ;
        }
        ?>

        <tbody>
    </table>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

<!--ce script pour le fonctionnement des deux btn delete & edit il prend en parametre #idDuTABLEAU et fait appelle à modifier.php-->
<script>

    $(document).ready(function(){
        $('#autoGeneratedID').Tabledit({
            url:'modifierSec.php',
            columns:{
                identifier:[0, "idSECRETAIRE"],
                editable:[[1, 'nom_s'], [2, 'prenom_s'],[3, 'numTel_s'], [4, 'niveau_s'],[5, 'adresse_s']]
            },
            restoreButton:false,
            onSuccess:function(data, textStatus, jqXHR)
            {
                if(data.action == 'delete')
                {
                    $('#'+data.id).remove();
                }
            }
        });


        /* ici c'est le script de dataTable au lieu de faire appelle à index.js on l'a copié ici pour que ça fonctionne*/

        $('#autoGeneratedID').dataTable({
            "columnDefs": [
                { "orderable": false, "targets": 0 }/*il y'avait 3 pour le double clique et modifier*/
            ]
        } );
        $('#autoGeneratedID td').attr('role', 'gridcell');
        $('#autoGeneratedID tr').attr('role', 'row');
        $('#autoGeneratedID th').attr('role', 'gridcell');
        $('#autoGeneratedID table').attr('role', 'grid');
        // $('#autoGeneratedID td:nth-of-type(-n+3)').attr('contenteditable', 'true');

    });

</script>
<!--pour afficher les btn delete et edit-->
<script src="js/jquery/jquery.tabledit.js"></script>

